### ISSUE TITLE
[ENCHANCEMENT] ANYONE STRUGGLING USE THIS:

### ISSUE THREAD

**Issue by aduriseti** [golfzaptw/action-connect-ovpn#141]
Couldnt figure out this action - but I ended up getting working using the approach in this coment: https://github.com/golfzaptw/action-connect-ovpn/issues/36#issuecomment-746201549

Basically:
1. dump your entire unencoded `.ovpn` file into a repo secret `OVPN_CONFIG`
2. write your username to repo secret `VPN_USER`
3. write your password to repo secret `VPN_PASS`

Use this block in your actions YAML file: 
```yaml
# ===============================================================================================
      # ========================================= VPN SETUP ===========================================
      # ===============================================================================================
      # BASED ON: https://github.com/golfzaptw/action-connect-ovpn/issues/36#issuecomment-746201549
      - name: Set Variables
        uses: allenevans/set-env@v2.0.0
        with:
          OVPN_CONFIG: ${{ secrets.OVPN_CONFIG }}
          VPN_USER: ${{ secrets.VPN_USER }}
          VPN_PASS: ${{ secrets.VPN_PASS }}
      - name: Write VPN Files
        run: |
          mkdir ~/.ssh
          echo "${OVPN_CONFIG}" > .github/vpn.ovpn
      - name: Install openvpn3
        run: |
          sudo apt install apt-transport-https
          sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
          sudo apt-key add openvpn-repo-pkg-key.pub
          DISTRO=`lsb_release -c -s`; sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-$DISTRO.list
          sudo apt update
          sudo apt install openvpn3
      - name: VPN Connect
        run: |
          echo ${VPN_USER}
          echo ${VPN_PASS}
          { echo ${VPN_USER} ; echo ${VPN_PASS} ; } | openvpn3 session-start --config .github/vpn.ovpn
      
      # ============== STUFF U NEED VPN FOR GOES HERE =====================
      # ..........................
      # ===================================================================

      
      - name: Kill VPN Connection
        if: always()
        run: |
          openvpn3 session-manage --disconnect --config .github/vpn.ovpn
      # ===============================================================================================
```
