### ISSUE TITLE
Need help understanding the connection flow

### ISSUE THREAD

**Issue by szabizs** [golfzaptw/action-connect-ovpn#26]
Thank you for your work.
I am unable to connect to my vpn server, maybe I don't understand something?

Here is my config.ovpn

```
client
proto udp
dev tun
ca ca.crt
dh dh2048.pem
cert user.crt
key user.key
remote hidden-vpn-server.com 1111
verb 2
mute 20
keepalive 10 120
persist-key
persist-tun
resolv-retry infinite
nobind
```

Then my CI, ca,cert,key are base64 enoded.

```
  connect-open-vpn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Open VPN
        run: sudo apt-get install openvpn
      - name: Connect VPN
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        with:
          PING_URL: '111.111.111.111'
          FILE_OVPN: '.github/vpn/config.ovpn'
          SECRET: ${{ secrets.SECRET_USERNAME_PASSWORD }}
        env:
          CA_CRT: ${{ secrets.CA_CRT}}
          USER_CRT: ${{ secrets.USER_CRT }}
          USER_KEY: ${{ secrets.USER_KEY }}
      - name: Check Connect VPN
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}
      - name: Ping dmz
        run: ping -c 1 111.111.111.111
```

But still got an error if i change 127.0.0.1 to my own dmz ip.
Could I get some help?

![image](https://user-images.githubusercontent.com/5064872/71730349-91fdac00-2e4a-11ea-8dac-fac934393215.png)

**Comment by golfzaptw** [comment]
@szabizs I think you lost this line in file ovpn `auth-user-pass secret.txt` or not?. Because you input SECRET in CI flow but in ovpn not use this.

**Comment by Elamurugan-Nallathambi** [comment]
The readme can be updated with more info I guess, for newbie like me not able to follow. 

I have openvpn file something like server.ovpn (AWS Custom installed VPN service) and I can able to connect to that using tunnelblick ios VPN client. Using same VPN file not sure how I should get these three data

 CA_CRT	
 USER_CRT	
 USER_KEY

When I connect to it now, am seeing this error

![Screen Shot 2020-03-23 at 2 42 06 PM](https://user-images.githubusercontent.com/54947876/77351675-79e44d00-6d14-11ea-9a58-ec90da854053.png)

**Comment by golfzaptw** [comment]
@Elamurugan-Nallathambi I saw your file. Do you have only tag `<ca> </ca>`, right ?

**Comment by Elamurugan-Nallathambi** [comment]
@golfzaptw so for these inputs from Github secrets I can just enter 

CA_CRT : <ca></ca>
USER_CRT : <cert></cert>
USER_KEY : < key ></key> ?

How I should pass my username and password to this?

**Comment by golfzaptw** [comment]
@Elamurugan-Nallathambi  Yes, You can inputs it in GitHub secrets with [base64](https://www.base64encode.org/)

**Comment by Elamurugan-Nallathambi** [comment]
if my username and password is something like below 

```
User: username
Password: password
```

then should I generate base64 with `username:password` or how I should generate?

Also regarding 

```
CA_CRT : <ca></ca>
USER_CRT : <cert></cert>
USER_KEY : <key></key>
```

I should just pass empty pairs like above?

**Comment by golfzaptw** [comment]
@Elamurugan-Nallathambi  You can set in file.ovpn
```
auth-user-pass secret.txt
ca ca.crt
cert user.crt
key user.key
```
and 
```
CA_CRT : <ca></ca>
USER_CRT : <cert></cert>
USER_KEY : <key></key>
```
can set
```
CA_CRT: ${{ secrets.CA_CRT}}
USER_CRT: ${{ secrets.USER_CRT }}
USER_KEY: ${{ secrets.USER_KEY }}
```

**Comment by golfzaptw** [comment]
@Elamurugan-Nallathambi  Username password you can use this
```
        with:
          PING_URL: '127.0.0.1'
          FILE_OVPN: '.github/vpn/config.ovpn'
          SECRET: ${{ secrets.SECRET_USERNAME_PASSWORD }}
```
and encode username password with base 64

example
```
my_user_name
my_password
```
after encode
`bXlfdXNlcl9uYW1lCm15X3Bhc3N3b3Jk`
and set after encode to GitHub Secrets

**Comment by Elamurugan-Nallathambi** [comment]
@golfzaptw This is what I did for entire process

My Actions VPN access setup looks like this

```
name: CI

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  connect-open-vpn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Open VPN
        run: sudo apt-get install openvpn
      - name: Connect VPN
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        with:
          PING_URL: '127.0.0.1'
          FILE_OVPN: '.github/ovpn.ovpn'
          SECRET: ${{ secrets.SECRET_USERNAME_PASSWORD }}
#           TLS_KEY: ${{ secrets.TLS_KEY }}
        env:
          CA_CRT: ${{ secrets.CA_CRT}}
          USER_CRT: ${{ secrets.USER_CRT }}
          USER_KEY: ${{ secrets.USER_KEY }}
      - name: Check Connect VPN
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}
      - name: kill vpn
        if: always()
        run: sudo killall openvpn
```

I have the `.github/ovpn.ovpn file` in github as following

```
client
dev tun
proto tcp
remote random_end_point.ENVIRONMENT.clientvpn.us-east-1.amazonaws.com 443
remote-random-hostname
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-GCM
verb 3
<ca>
-----BEGIN CERTIFICATE-----
[random_keys_provided_by_admin]
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
[random_keys_provided_by_admin]
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
[random_keys_provided_by_admin]
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
[random_keys_provided_by_admin]
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
[random_keys_provided_by_admin]
-----END CERTIFICATE-----

</ca>
auth-user-pass
reneg-sec 0
```

**Note:** 
Replaced `actual keys with "[random_keys_provided_by_admin]",` `remote url with ramdom_url` in above context

In the above `.github/ovpn.ovpn file` added [On top of the file]

```
auth-user-pass secret.txt
ca ca.crt
cert user.crt
key user.key
```

Defined the secret keys like you mentioned

![Screen Shot 2020-03-25 at 1 11 45 PM](https://user-images.githubusercontent.com/54947876/77565147-2f8cd880-6e9a-11ea-88c8-2e9180fc8ae3.png)


When it executes this is what I get
![Screen Shot 2020-03-25 at 1 09 39 PM](https://user-images.githubusercontent.com/54947876/77564961-e5a3f280-6e99-11ea-99cb-4b569060aad9.png)


_This is from AWS and I can able to connect to this VPN using TunnelBlick client._

**Comment by AdamSlack** [comment]
@Elamurugan-Nallathambi I'm encountering what appears to be the same problem. an AWS VPN which i can connect to just fine with openvpn3 via the command line.

@golfzaptw some more detailed instructions/examples on what config this GitHub action requires would be very useful!

**Comment by AdamSlack** [comment]
In the end we just went and installed openvpn3 as part of the pipeline and writing things to a file. Was much easier.

```yml
    - name: set-env-vars
      uses: allenevans/set-env@v1.1.0
      with:
        CA_CRT: ${{ secrets.CA_CRT}}
        CLIENT_CRT: ${{ secrets.CLIENT_CRT }}
        CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
        TA_KEY: ${{ secrets.TA_KEY }}

    - name: Write VPN Files
      run: |
        echo "$CA_CRT" > .github/vpn/ca.crt
        echo "$CLIENT_CRT" > .github/vpn/client.crt
        echo "$CLIENT_KEY" > .github/vpn/client.key
        echo "$TA_KEY" > .github/vpn/ta.key

    - name: Install Open VPN
      run: |
        sudo apt install apt-transport-https
        sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
        sudo apt-key add openvpn-repo-pkg-key.pub
        sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-bionic.list
        sudo apt update
        sudo apt install openvpn3
    - name: Start Open VPN 3
      run: openvpn3 session-start --config .github/vpn/iw_vpn.ovpn

```
