### ISSUE TITLE
Error while connecting VPN

### ISSUE THREAD

**Issue by gau1991** [golfzaptw/action-connect-ovpn#36]
**Describe the bug**
We are trying to use this action and each time we are gettting following error:

```
/bin/sh: 37: ***: not found
/bin/sh: 38: ***: not found
/bin/sh: 39: ***: not found
/bin/sh: 40: ***: not found
/bin/sh: 41: ***: not found
/bin/sh: 42: ***: not found
/bin/sh: 43: ***: not found
/bin/sh: 44: ***: not found
/bin/sh: 45: ***: not found
/bin/sh: 46: ***: not found
/bin/sh: 47: ***: not found
/bin/sh: 48: ***: not found
/bin/sh: 49: ***: not found
/bin/sh: 50: ***: not found
/bin/sh: 51: ***: not found
/bin/sh: 52: -----END: not found
Failed to query password: Timer expired
##[error]Can't setup config /home/runner/work/Connect-VPN/Connect-VPN/.github/vpn/config.ovpn
Failed to query password: Timer expired
```

Our OVPN looks like following:
```
setenv UV_ID XXXX
setenv UV_NAME XXXX
client
dev tun
dev-type tun
remote XXXXXXXX 17048 udp
nobind
persist-tun
cipher AES-128-CBC
auth SHA256
verb 2
mute 3
push-peer-info
ping 10
ping-restart 60
hand-window 70
server-poll-timeout 4
reneg-sec 2592000
sndbuf 393216
rcvbuf 393216
max-routes 1000
remote-cert-tls server
comp-lzo no
auth-user-pass secret.txt
key-direction 1
ca ca.crt
tls-auth tls.key
cert user.crt
key user.key
```

**Comment by vanneback** [comment]
Im getting a similar issue. Not exact but have alot of ***: not found

**Comment by kritzware** [comment]
Any updates @golfzaptw ? Also getting this error

**Comment by kritzware** [comment]
My solution in the end @vanneback was to manually connect to OpenVPN (not using this action)
```
openvpn connect --config <config-filepath> --daemon
```
I store the certificates as secrets, and inject them into the config via GitHub secrets. You may need `--auth-user-pass` as well depending on your vpn setup.

**Comment by alterx** [comment]
I'm facing the same issue here, so I ended up just manually connecting just as @kritzware 

What are you using to make sure you ping the url until the vpn is up @kritzware ?

**Comment by golfzaptw** [comment]
@kritzware sorry for my late. I can't reproduce for that step. can u give your workflow?

**Comment by AdamSlack** [comment]
Encountered the same problems described in this issue, and i think ultimately went the same route as @kritzware 

```yml
    - name: set-env-common
      uses: allenevans/set-env@v1.1.0
      with:
        CA_CRT: ${{ secrets.CA_CRT}}
        CLIENT_CRT: ${{ secrets.CLIENT_CRT }}
        CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
        TA_KEY: ${{ secrets.TA_KEY }}

    - name: Write VPN Files
      run: |
        echo "$CA_CRT" > .github/vpn/ca.crt
        echo "$CLIENT_CRT" > .github/vpn/client.crt
        echo "$CLIENT_KEY" > .github/vpn/client.key
        echo "$TA_KEY" > .github/vpn/ta.key

    - name: Install Open VPN
      run: |
        sudo apt install apt-transport-https
        sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
        sudo apt-key add openvpn-repo-pkg-key.pub
        sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-bionic.list
        sudo apt update
        sudo apt install openvpn3

    - name: Start Open VPN 3
      run: openvpn3 session-start --config .github/vpn/vpn.ovpn
```

**Comment by paul-uz** [comment]
@AdamSlack what does your `.ovpn` file look like? 

How are you telling OpenVPN to use the cert/key files?

**Comment by tomitrescak** [comment]
Shame he never responded 👎 I could really use this answer ;/

**Comment by tomitrescak** [comment]
How do you "inject secrets into ovpn.config"?

**Comment by tomitrescak** [comment]
Here is my solution in case you have a username and password.

1. Keep the WHOLE ovpn in a secret, no need to mess around with all different files
2. Keep your passwordin a secret, you can also keep your user if you need

Here is the config:

```
      - name: Set Variables
        uses: allenevans/set-env@v2.0.0
        with:
          OVPN: ${{ secrets.OVPN}}
          VPN_SECRET: ${{ secrets.VPN_SECRET }}
      - name: Write VPN Files
        run: |
          mkdir ~/.ssh
          echo "$OVPN" > .github/vpn.ovpn
      - name: Install Open VPN
        run: |
          git remote add deploy $DEPLOY_URL
          sudo apt install apt-transport-https
          sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
          sudo apt-key add openvpn-repo-pkg-key.pub
          sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-bionic.list
          sudo apt update
          sudo apt install openvpn3

      - name: Start Open VPN 3
        run: |
          { echo user ; echo $VPN_SECRET ; } | openvpn3 session-start --config .github/vpn.ovpn
```

**Comment by AdamSlack** [comment]
@paul-uz, @tomitrescak, sorry for the delayed response. Hope you were able to find a solution as well!

My approach involved storing various elements as GitHub secrets and then writing them to a file:

```
    - name: Write VPN Files
      run: |
        echo "$CA_CRT" > .github/vpn/ca.crt
        echo "$CLIENT_CRT" > .github/vpn/client.crt
        echo "$CLIENT_KEY" > .github/vpn/client.key
        echo "$TA_KEY" > .github/vpn/ta.key
```

The 4 files: `ca.crt`, `client.crt`, `client.key`, and `ta.key` were then referenced in the `.ovpn` file like the following:
```
ca ca.crt
cert client.crt
key client.key
tls-auth ta.key 1
```

**Comment by AdamSlack** [comment]
I do think putting the whole OVPN file into a GH Secret as @tomitrescak would be an easier workaround!

**Comment by zigang93** [comment]
> Here is my solution in case you have a username and password.
> 
> 1. Keep the WHOLE ovpn in a secret, no need to mess around with all different files
> 2. Keep your passwordin a secret, you can also keep your user if you need
> 
> Here is the config:
> 
> ```
>       - name: Set Variables
>         uses: allenevans/set-env@v2.0.0
>         with:
>           OVPN: ${{ secrets.OVPN}}
>           VPN_SECRET: ${{ secrets.VPN_SECRET }}
>       - name: Write VPN Files
>         run: |
>           mkdir ~/.ssh
>           echo "$OVPN" > .github/vpn.ovpn
>       - name: Install Open VPN
>         run: |
>           git remote add deploy $DEPLOY_URL
>           sudo apt install apt-transport-https
>           sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
>           sudo apt-key add openvpn-repo-pkg-key.pub
>           sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-bionic.list
>           sudo apt update
>           sudo apt install openvpn3
> 
>       - name: Start Open VPN 3
>         run: |
>           { echo user ; echo $VPN_SECRET ; } | openvpn3 session-start --config .github/vpn.ovpn
> ```

what is VPN_SECRET mean??
username and password? 
sorry I am quite new to VPN stuff

**Comment by tomitrescak** [comment]
That would be your password. Also on this line you replase $user with actual VPN user

>>  { echo $user; echo $VPN_SECRET ; } | openvpn3 session-start --config .github/vpn.ovpn

**Comment by LibanaAbdul** [comment]
> Here is my solution in case you have a username and password.
> 
>     1. Keep the WHOLE ovpn in a secret, no need to mess around with all different files
> 
>     2. Keep your passwordin a secret, you can also keep your user if you need
> 
> 
> Here is the config:
> 
> ```
>       - name: Set Variables
>         uses: allenevans/set-env@v2.0.0
>         with:
>           OVPN: ${{ secrets.OVPN}}
>           VPN_SECRET: ${{ secrets.VPN_SECRET }}
>       - name: Write VPN Files
>         run: |
>           mkdir ~/.ssh
>           echo "$OVPN" > .github/vpn.ovpn
>       - name: Install Open VPN
>         run: |
>           git remote add deploy $DEPLOY_URL
>           sudo apt install apt-transport-https
>           sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
>           sudo apt-key add openvpn-repo-pkg-key.pub
>           sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-bionic.list
>           sudo apt update
>           sudo apt install openvpn3
> 
>       - name: Start Open VPN 3
>         run: |
>           { echo user ; echo $VPN_SECRET ; } | openvpn3 session-start --config .github/vpn.ovpn
> ```

Hi @tomitrescak how are you, I'm applying your solution, but I get the following error. 

**`up]Run mkdir ~/.ssh
  mkdir ~/.ssh
  echo "$OVPN" > .github/vpn.ovpn
  shell: /usr/bin/bash -e {0}
  env:
    OVPN: ***
    VPN_SECRET: ***
/home/runner/work/_temp/b96210c7-df49-46c2-a346-269ac6fb45ca.sh: line 2: .github/vpn.ovpn: No such file or directory
Error: or]Process completed with exit code 1.`**

**Comment by Smalto22** [comment]
> Encountered the same problems described in this issue, and i think ultimately went the same route as @kritzware
> 
> ```yaml
>     - name: set-env-common
>       uses: allenevans/set-env@v1.1.0
>       with:
>         CA_CRT: ${{ secrets.CA_CRT}}
>         CLIENT_CRT: ${{ secrets.CLIENT_CRT }}
>         CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
>         TA_KEY: ${{ secrets.TA_KEY }}
> 
>     - name: Write VPN Files
>       run: |
>         echo "$CA_CRT" > .github/vpn/ca.crt
>         echo "$CLIENT_CRT" > .github/vpn/client.crt
>         echo "$CLIENT_KEY" > .github/vpn/client.key
>         echo "$TA_KEY" > .github/vpn/ta.key
> 
>     - name: Install Open VPN
>       run: |
>         sudo apt install apt-transport-https
>         sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
>         sudo apt-key add openvpn-repo-pkg-key.pub
>         sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-bionic.list
>         sudo apt update
>         sudo apt install openvpn3
> 
>     - name: Start Open VPN 3
>       run: openvpn3 session-start --config .github/vpn/vpn.ovpn
> ```

Just posting an update to the solution by @AdamSlack since the set-env command is now deprecated:

```yml
      - name: Set VPN env
        run: |
          echo "ca_crt<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.CA_CRT }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "client_crt<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.CLIENT_CRT }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "client_key<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.CLIENT_KEY }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "ta_key<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.TA_KEY }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Write VPN Files
        run: |
          echo "${{ env.ca_crt }}" > .github/vpn/ca.crt
          echo "${{ env.client_crt }}" > .github/vpn/client.crt
          echo "${{ env.client_key }}" > .github/vpn/client.key
          echo "${{ env.ta_key }}" > .github/vpn/ta.key

      - name: Install Open VPN
        run: |
          sudo apt install apt-transport-https
          sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
          sudo apt-key add openvpn-repo-pkg-key.pub
          sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-bionic.list
          sudo apt update
          sudo apt install openvpn3

      - name: Start Open VPN 3
        run: openvpn3 session-start --config .github/vpn/Consnet.ovpn
```

**Comment by martijngastkemper** [comment]
I used @Smalto22 step as starting point. I ended up merging "Set VPN env" and "Write VPN Files". Use OpenVPN 2.

```
      - name: Write VPN Files
        run: |
          echo "${{ secrets.CA_CRT }}" > ca.crt
          echo "${{ secrets.CLIENT_CRT }}" > client.crt
          echo "${{ secrets.CLIENT_KEY }}" > client.key
          echo "${{ secrets.TA_KEY }}" > ta.key

      - name: Install Open VPN
        run: sudo apt install openvpn
```

To answer @alterx question about waiting for the OpenVPN connection to be ready:

```
      - name: Connect VPN
        run: sudo openvpn --config ".github/vpn/config.ovpn" --log "vpn.log" --daemon

      - name: Wait for a connection
        run: until ping -c1 10.86.25.7; do sleep 2; done
```

The last part is killing openvpn and uploading the log file. Because of `--daemon` stdout is empty.

```
      - name: Kill VPN connection
        if: always()
        run: |
          sudo chmod 777 vpn.log
          sudo killall openvpn

      - name: Upload VPN logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: VPN logs
          path: vpn.log
```

Notice the `sudo chmod`. That necessary to give `upload-artifact` read access to the log file.
