### ISSUE TITLE
connect error: Can't setup config

### ISSUE THREAD

**Issue by kmr299** [golfzaptw/action-connect-ovpn#45]
Please can you help me with this problem?

**Describe the bug**
I'm trying to connect to my vpn and the following error message appears: Can't setup config /home/runner/work/auth_api/auth_api/.github/vpn/config.ovpn

**Additional context**
My OVPN config:

```
client
dev tun
proto tcp
verify-x509-name "C=BR, ST=Sao Paulo, L=Sao Paulo, O=xxxxxxxxxxxxxxxxxxx, OU=OU, CN=xxxxxxxxxxxxxxxxxxxxxxxxx, emailAddress=xxxxx@xxxx.xxx.xx"
route remote_host 255.255.255.255 net_gateway
resolv-retry infinite
nobind
persist-key
persist-tun
ca ca.crt
cert user.crt
key user.key
auth-user-pass
cipher AES-128-CBC
auth SHA256
comp-lzo yes
route-delay 4
verb 3
reneg-sec 0
remote xxxxxxxxxxxxxx
remote xxxxxxxxxxxxxx

```

My yml config:
```
name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Open VPN
      run: sudo apt-get install openvpn
    
    - name: Connect VPN
      uses: golfzaptw/action-connect-ovpn@master
      id: connect_vpn
      with:
        PING_URL: '10.23.24.47'
        FILE_OVPN: '.github/vpn/config.ovpn'
        SECRET: ${{ secrets.VPN_USER_PASSWORD_SPACE }}
      env:
        CA_CRT: ${{ secrets.VPN_CA}}
        USER_CRT: ${{ secrets.VPN_CERT }}
        USER_KEY: ${{ secrets.VPN_KEY }}
```
