### ISSUE TITLE
base64: invalid input 

### ISSUE THREAD

**Issue by MatteoGioioso** [golfzaptw/action-connect-ovpn#56]
**Describe the bug**
this is the error I keep getting:

```
base64: invalid input
##[error]Can't create file user.key
```

If I execute this script in my local machine `echo <my_base_64_key> |base64 -d >>  user.key` I get no error.
Does the key have to be input without ?
```
-----BEGIN RSA PRIVATE KEY-----
```

and 

```
-----END RSA PRIVATE KEY-----
```

This is my `workflow.yaml` file

```yaml

name: PR status checks
on:
  pull_request:
    branches:
      - develop
    types: [assigned, opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: develop
      - uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_STATUS_CHECK }}
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - name: Install and build
        run: npm install

      - name: Install Open VPN
        run: sudo apt-get install openvpn

      - name: Connect VPN
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        with:
          PING_URL: '127.0.0.1'
          FILE_OVPN: 'config/config.ovpn'
        env:
          CA_CRT: ${{ secrets.CA_CRT}}
          USER_CRT: ${{ secrets.USER_CRT }}
          USER_KEY: ${{ secrets.USER_KEY }}
      - name: Check Connect VPN
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}

       ...

      - name: kill vpn
        if: always()
        run: sudo killall openvp


```
